 Form.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.verticalLayout_3 = QVBoxLayout(Form)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(50, 50, 50, 50)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_3)

        self.frame_3 = QFrame(Form)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QSize(737, 100))
        self.frame_3.setMaximumSize(QSize(16777215, 150))
        self.frame_3.setStyleSheet(u"")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(181, 30, 375, 31))
        self.label.setStyleSheet(u"font: 700 24pt \"Segoe UI\";")
        self.line_2 = QFrame(self.frame_3)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(-2, 90, 1521, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)

        self.horizontalLayout.addWidget(self.frame_3)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_4)


        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_4.addItem(self.verticalSpacer_2)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)

        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(800, 400))
        self.frame.setStyleSheet(u"")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.pushButton = QPushButton(self.frame)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(255, 350, 140, 24))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(319, 5, 161, 31))
        self.label_6.setMinimumSize(QSize(161, 31))
        self.label_6.setMaximumSize(QSize(161, 31))
        self.label_6.setStyleSheet(u"font: 700 16pt \"Segoe UI\";")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(70, 180, 80, 16))
        self.label_4.setStyleSheet(u"font: 700 10pt \"Segoe UI\";")
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 140, 80, 16))
        self.label_3.setStyleSheet(u"font: 700 10pt \"Segoe UI\";")
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(70, 220, 80, 16))
        self.label_5.setStyleSheet(u"font: 700 10pt \"Segoe UI\";")
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 100, 80, 16))
        self.label_2.setStyleSheet(u"font: 700 10pt \"Segoe UI\";")
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(470, 60, 80, 16))
        self.label_9.setStyleSheet(u"font: 700 10pt \"Segoe UI\";")
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(470, 140, 80, 16))
        self.label_10.setStyleSheet(u"font: 700 10pt \"Segoe UI\";")
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(470, 100, 80, 16))
        self.label_11.setStyleSheet(u"font: 700 10pt \"Segoe UI\";")
        self.label_12 = QLabel(self.frame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(470, 180, 80, 16))
        self.label_12.setStyleSheet(u"font: 700 10pt \"Segoe UI\";")
        
        self.lineEdit = QLineEdit(self.frame)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(150, 90, 180, 31))
        self.lineEdit_3 = QLineEdit(self.frame)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(150, 170, 180, 31))
        self.lineEdit_4 = QLineEdit(self.frame)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(150, 210, 180, 31))
        self.lineEdit_5 = QLineEdit(self.frame)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(550, 170, 180, 31))
        self.lineEdit_6 = QLineEdit(self.frame)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(550, 130, 180, 31))
        
        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(425, 350, 140, 24))
        self.frame_4 = QFrame(self.frame)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(70, 260, 60, 60))
        self.frame_4.setStyleSheet(u"background-color: rgb(0, 85, 255);\n""border-radius: 30px;")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_13 = QLabel(self.frame)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(140, 270, 71, 16))
        self.label_13.setStyleSheet(u"font: 700 10pt \"Segoe UI\";")
        self.pushButton_3 = QPushButton(self.frame)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(140, 300, 61, 21))
        self.pushButton_4 = QPushButton(self.frame)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(210, 300, 61, 21))
        self.label_14 = QLabel(self.frame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(210, 270, 71, 16))
        self.label_14.setStyleSheet(u"")
        self.dateEdit = QDateEdit(self.frame)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(150, 130, 180, 31))
        self.comboBox = QComboBox(self.frame)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(550, 90, 180, 31))
        self.comboBox_2 = QComboBox(self.frame)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(550, 50, 180, 31))
        self.label_15 = QLabel(self.frame)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(470, 220, 80, 16))
        self.label_15.setStyleSheet(u"font: 700 10pt \"Segoe UI\";")
        self.comboBox_3 = QComboBox(self.frame)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(550, 210, 180, 31))
        self.lineEdit_2 = QLineEdit(self.frame)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(150, 50, 180, 31))
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(70, 60, 80, 16))
        self.label_7.setStyleSheet(u"font: 700 10pt \"Segoe UI\";")

        self.horizontalLayout_2.addWidget(self.frame)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)


        self.verticalLayout_4.addLayout(self.horizontalLayout_2)


        self.verticalLayout_3.addLayout(self.verticalLayout_4)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_3.addItem(self.verticalSpacer)


        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"CADASTRO DE USU\u00c1RIO", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"Salvar altera\u00e7\u00f5es", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Dados pessoais:", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Email:", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Data Nasc:", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"Celular:", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Sobrenome:", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Estado:", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Rua:", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Cidade:", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Bairro:", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"Cancelar", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"Foto atual:", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"Carregar", None))
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"Remover", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"foto.png", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"Cargo:", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("Form", u"-------------", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("Form", u"Administrador", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("Form", u"Cozinheiro", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("Form", u"Estoquista", None))

        self.label_7.setText(QCoreApplication.translate("Form", u"Nome:", None))
    # retranslateUi